
import com.sun.glass.ui.Window;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MOHAMED SHABEER KP
 */
public class Main extends javax.swing.JFrame {

    String path;
    File file;
    DefaultTableModel display_table_model;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header_panel = new javax.swing.JPanel();
        file_name_label = new javax.swing.JLabel();
        main_table_panel = new javax.swing.JPanel();
        main_table_scroll_panel = new javax.swing.JScrollPane();
        main_table = new javax.swing.JTable();
        reg_selection_panel = new javax.swing.JPanel();
        selection_panel = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        select_button = new javax.swing.JButton();
        result_display_panel = new javax.swing.JPanel();
        submit_panel = new javax.swing.JPanel();
        submit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ID CARD AUTOMATED GENERATION [MULTIPLE]- BETA 1.0");
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(1630, 820));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 150, 221), 4, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1510, 715));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 34, 160), 4, true));
        header_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file_name_label.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        file_name_label.setText("WELCOME TO ID CARD GENERATOR [MULTIPLE]");
        header_panel.add(file_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 520, 30));

        jPanel1.add(header_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 7, 1200, 39));

        main_table_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 192, 197), 2, true));
        main_table_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    main_table.getTableHeader().setReorderingAllowed(false);
    main_table_scroll_panel.setViewportView(main_table);

    main_table_panel.add(main_table_scroll_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 560));

    jPanel1.add(main_table_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 58, -1, 560));

    reg_selection_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 55, 209), 3, true));
    reg_selection_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    selection_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 3, true));
    selection_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    welcome_label.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    welcome_label.setText("ID CARD GENERATOR");
    selection_panel.add(welcome_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, -1));

    select_button.setBackground(new java.awt.Color(51, 153, 255));
    select_button.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    select_button.setForeground(new java.awt.Color(255, 255, 255));
    select_button.setText("SELECT CSV FILE");
    select_button.setToolTipText("Click here to select the excel file (.csv).");
    select_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            select_buttonActionPerformed(evt);
        }
    });
    selection_panel.add(select_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 50));

    reg_selection_panel.add(selection_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 10, 260, 180));

    jPanel1.add(reg_selection_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 12, 283, 610));

    result_display_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 192, 197), 2, true));
    result_display_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    jPanel1.add(result_display_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 552, -1, -1));

    submit_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    submit_button.setVisible(false);
    submit_button.setBackground(new java.awt.Color(51, 153, 255));
    submit_button.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    submit_button.setForeground(new java.awt.Color(255, 255, 255));
    submit_button.setText("SUBMIT");
    submit_button.setToolTipText("Click this button for generating the ID card of the selected student.");
    submit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    submit_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            submit_buttonActionPerformed(evt);
        }
    });
    submit_panel.add(submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 200, 64));

    jPanel1.add(submit_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 1490, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(76, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(65, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        this.dispose();
  
        new Design((DefaultTableModel)main_table.getModel()).setVisible(true);
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_buttonActionPerformed
        JFileChooser jfc = new JFileChooser();
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedSourceFile = jfc.getSelectedFile();
            String fname=selectedSourceFile.getName();
            int typePos =fname.lastIndexOf(".");
            String ftype=fname.substring(typePos,fname.length());

            if(".csv".equals(ftype))
            {
                file_name_label.setText(fname);
                path=selectedSourceFile.getAbsolutePath();

                file =new File(path);
                try {

                    BufferedReader br = new BufferedReader(new FileReader(file));
                    String firstLine = br.readLine().trim();
                    String[] columnsName = firstLine.split(",");

                    DefaultTableModel model =(DefaultTableModel)main_table.getModel();
                    model.setRowCount(0);
                    model.setColumnIdentifiers(columnsName);

                    Object[] tableLines = br.lines().toArray();

                    for(int i =0;i<tableLines.length;i++)
                    {
                        String line = tableLines[i].toString().trim();
                        String[] dataRow = line.split(",");
                        model.addRow(dataRow);
                    }

                    submit_button.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            else
            JOptionPane.showMessageDialog(null, "Select A Valid CSV file", "Invalid File " , JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_select_buttonActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel file_name_label;
    private javax.swing.JPanel header_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable main_table;
    private javax.swing.JPanel main_table_panel;
    private javax.swing.JScrollPane main_table_scroll_panel;
    private javax.swing.JPanel reg_selection_panel;
    private javax.swing.JPanel result_display_panel;
    private javax.swing.JButton select_button;
    private javax.swing.JPanel selection_panel;
    private javax.swing.JButton submit_button;
    private javax.swing.JPanel submit_panel;
    private javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
}
